k8screen-api:
  base-url: ${API_BASE_URL:http://localhost:8080}

k8screen-db:
  host: ${K8SCREEN_DB_HOST:localhost}
  port: ${K8SCREEN_DB_PORT:5432}
  db: ${K8SCREEN_DB_DATABASE:k8screen}
  username: ${K8SCREEN_DB_USERNAME:admin}
  password: ${K8SCREEN_DB_PASSWORD:admin123}
  url: jdbc:postgresql://${k8screen-db.host}:${k8screen-db.port}/${k8screen-db.db}

k8screen-frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
  login-url: ${k8screen-frontend.base-url}/login
  success-url: ${k8screen-frontend.base-url}/login

k8screen:
  config:
    path: ${user.home}/.k8screen/configs

spring:
  datasource:
    url: ${k8screen-db.url}
    driver-class-name: org.postgresql.Driver
    username: ${k8screen-db.username}
    password: ${k8screen-db.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: http://localhost:5173
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
