server:
  port: 8080

logging:
  level:
    root: WARN
    org.yaml.snakeyaml.introspector: ERROR

k8screen-db:
  host: ${K8SCREEN_DB_HOST:localhost}
  port: ${K8SCREEN_DB_PORT:5432}
  db: ${K8SCREEN_DB_DATABASE:k8screen}
  username: ${K8SCREEN_DB_USERNAME:admin}
  password: ${K8SCREEN_DB_PASSWORD:admin123}
  url: jdbc:postgresql://${k8screen-db.host}:${k8screen-db.port}/${k8screen-db.db}

k8screen-frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:5173}
  login-url: ${k8screen-frontend.base-url}/login
  success-url: ${k8screen-frontend.base-url}/login

k8screen:
  config:
    path: ${user.home}/.k8screen/configs
  trash:
    path: ${k8screen.config.path}/trash

stripe:
  enable: false
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:YOUR_STRIPE_PUBLISHABLE_KEY}
  secret-key: ${STRIPE_SECRET_KEY:YOUR_STRIPE_SECRET_KEY}
  product:
    price-id:
      free: price_1RfM9UIsjyVn3MvbJBsnDfFz
      standard: price_1RfME2IsjyVn3Mvbo1AH8S4G
      premium: price_1RfMECIsjyVn3MvbrpBWaMWb
  webhook:
    signature-key: ${STRIPE_WEBHOOK_SIGNATURE_KEY:YOUR_STRIPE_WEBHOOK_SIGNATURE_KEY}

spring:
  datasource:
    url: ${k8screen-db.url}
    driver-class-name: org.postgresql.Driver
    username: ${k8screen-db.username}
    password: ${k8screen-db.password}

  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        globally_quoted_identifiers: true

  flyway:
    baseline-on-migrate: true
    baseline-description: "init"
    baseline-version: 0
    enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: http://localhost:5173
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
