name: k8screen CD

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  k8screen:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Create jar files and run unit tests
        run: ./mvnw -ntp -B package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3.4.0
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Detect Image Tag
        id: image-version
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            DOCKER_IMAGE_TAG="${GITHUB_REF_NAME#v}"
          else
            DOCKER_IMAGE_TAG="`echo ${GITHUB_SHA::7}`"
          fi
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and Push
        uses: docker/build-push-action@v6.18.0
        with:
          context: k8screen-backend
          push: true
          tags: registry.gitlab.com/mansurcildir/reg/k8screen-backend:${{ env.DOCKER_IMAGE_TAG }},registry.gitlab.com/mansurcildir/reg/k8screen-backend:latest
